# Generated by Django 4.2.19 on 2025-10-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lti_provider', '0004_require_user_account'), # Latest lti_provider migration
    ]

    operations = [
        migrations.CreateModel(
            name='GradedAssignmentExtra',
            fields=[
                ('gradedassignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='lti_provider.gradedassignment')),
                ('lis_result_sourcedid_long', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lti_provider_gradedassignment_extra',
            },
        ),
    ]
